/*  Simplied and enhanced version of fetch API  */
const serverURL = process.env.NODE_ENV === 'development' ?
  'http://localhost:3100' : 'https://api.carllllo.work/covid19';
const RETRY_TIMES = 3;
let retryCount = 0;

function fetchJSON(api, init) {
  // If no response in 5 seconds, abort the request
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), 6000);

  // convert init object to query string
  let params = '';
  if (init) {
    params = '?' + Object.keys(init).map((key) => {
      return key + '=' + init[key];
    }).join('&');
  }

  // Add timestamp to avoid cache result
  const requestURL = serverURL + api + params;
  // return a promise generated by a 'post' fetch
  return fetch(requestURL, {
    method: 'get',
    headers: {'Content-Type': 'application/json;charset=utf-8'},
    signal: controller.signal
  })
    .then((body) => {
      // cancel the abortion timer when response arrived
      clearTimeout(id);
      if (body.ok) {
        return body.json();
      } else {
        throw new Error('Request failed: ' +
          body.status + ' ' + body.statusText);
      }
    })
    // retry while request failed
    .catch((err) => {
      if (err.message.includes('404')) {
        alert('该资源不存在');
        return Promise.reject(err);
      } else if (err.message.includes('504')) {
        alert('服务器超时（504），请耐心等待修复');
        return Promise.reject(err);
      } else if (retryCount > RETRY_TIMES) {
        retryCount = 0;
        console.log('请求超时，请重试。');
        console.log(err);
        if (err.name === 'AbortError') {
          alert('服务器长时间无响应，请检查您的网络');
          return Promise.reject(new Error('Request timeout'));
        }
      } else {
        // remind the user if retry for twice or more
        if (err.name === 'AbortError' && retryCount > 1) {
          alert('网络似乎有点慢，正在重试……');
        }
        retryCount++;
        // try again in (500*retryCount)ms
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve(fetchJSON(api, init));
          }, 500 * retryCount);
        });
      }
    });
}

export default fetchJSON;
