// contains all countries in echarts world map
const nameMap = {
  'Afghanistan': '阿富汗',
  'Aland': '奥兰',
  'Albania': '阿尔巴尼亚',
  'Algeria': '阿尔及利亚',
  'American Samoa': '',
  'Andorra': '安道尔',
  'Angola': '安圭拉',
  'Antarctica': '南极洲',
  'Antigua and Barb.': '安提瓜和巴布达',
  'Argentina': '阿根廷',
  'Armenia': '亚美尼亚',
  'Australia': '澳大利亚',
  'Austria': '奥地利',
  'Azerbaijan': '阿塞拜疆',
  'Bahamas': '巴哈马',
  'Bahrain': '巴林',
  'Bangladesh': '孟加拉国',
  'Barbados': '巴巴多斯',
  'Belarus': '白俄罗斯',
  'Belgium': '比利时',
  'Belize': '伯利兹',
  'Benin': '贝宁',
  'Bermuda': '百慕大',
  'Bhutan': '不丹',
  'Bolivia': '玻利维亚',
  'Bosnia and Herz.': '波斯尼亚和黑塞哥维那',
  'Botswana': '博茨瓦纳',
  'Brazil': '巴西',
  'Br. Indian Ocean Ter.': '英屬印度洋領地',
  'Brunei': '文莱',
  'Bulgaria': '保加利亚',
  'Burkina Faso': '布基纳法索',
  'Burundi': '布隆迪',
  'Cambodia': '柬埔寨',
  'Cameroon': '喀麦隆',
  'Canada': '加拿大',
  'Cape Verde': '佛得角',
  'Cayman Is.': '开曼群岛',
  'Central African Rep.': '中非共和国',
  'Chad': '乍得',
  'Chile': '智利',
  'China': '中国',
  'Colombia': '哥伦比亚',
  'Comoros': '科摩罗',
  'Costa Rica': '哥斯达黎加',
  'Côte d\'Ivoire': '科特迪瓦',
  'Croatia': '克罗地亚',
  'Cuba': '古巴',
  'Curaçao': '库拉索岛',
  'Cyprus': '塞浦路斯',
  'Czech Rep.': '捷克共和国',
  'Dem. Rep. Congo': '刚果（金）',
  'Denmark': '丹麦',
  'Djibouti': '吉布提',
  'Dominica': '多米尼加',
  'Dominican Rep.': '多明尼加共和国',
  'Ecuador': '厄瓜多尔',
  'Egypt': '埃及',
  'El Salvador': '萨尔瓦多',
  'Eq. Guinea': '赤道几内亚',
  'Eritrea': '厄立特里亚',
  'Estonia': '爱沙尼亚',
  'Ethiopia': '埃塞俄比亚',
  'Falkland Is.': '福克兰群岛',
  'Faeroe Is.': '法罗群岛',
  'Fiji': '斐济',
  'Finland': '芬兰',
  'France': '法国',
  'French Guiana': '法属圭亚那',
  'Fr. S. Antarctic Lands': '法属南部和南极领地',
  'Fr. Polynesia': '',
  'Gabon': '加蓬',
  'Gambia': '冈比亚',
  'Gaza Strip': '加沙',
  'Georgia': '格鲁吉亚',
  'Germany': '德国',
  'Ghana': '加纳',
  'Greece': '希腊',
  'Greenland': '格陵兰',
  'Grenada': '格林那达',
  'Guadeloupe': '瓜德罗普',
  'Guam': '关岛',
  'Guatemala': '危地马拉',
  'Guinea': '几内亚',
  'Guinea-Bissau': '几内亚比绍',
  'Guyana': '圭亚那',
  'Haiti': '海地',
  'Heard I. and McDonald Is.': '赫德岛和麦克唐纳群岛',
  'Honduras': '洪都拉斯',
  'Hong Kong': '香港',
  'Hungary': '匈牙利',
  'Iceland': '冰岛',
  'India': '印度',
  'Indonesia': '印度尼西亚',
  'Iran': '伊朗',
  'Iraq': '伊拉克',
  'Iraq-Saudi Arabia Neutral Zone': '伊拉克阿拉伯中立区',
  'Ireland': '爱尔兰',
  'Isle of Man': '马恩岛',
  'Israel': '以色列',
  'Italy': '意大利',
  'Jamaica': '牙买加',
  'Jan Mayen': '扬马延岛',
  'Japan': '日本',
  'Jersey': '泽西',
  'Jordan': '约旦',
  'Kazakhstan': '哈萨克斯坦',
  'Kenya': '肯尼亚',
  'Kerguelen': '凯尔盖朗群岛',
  'Kiribati': '基里巴斯',
  'Dem. Rep. Korea': '朝鲜',
  'Korea': '韩国',
  'Kosovo': '科索沃',
  'Kuwait': '科威特',
  'Kyrgyzstan': '吉尔吉斯斯坦',
  'Lao PDR': '老挝',
  'Latvia': '拉脱维亚',
  'Lebanon': '黎巴嫩',
  'Lesotho': '莱索托',
  'Liberia': '利比里亚',
  'Libya': '利比亚',
  'Liechtenstein': '列支敦士登',
  'Lithuania': '立陶宛',
  'Luxembourg': '卢森堡',
  'Macau': '澳门',
  'Macedonia': '马其顿',
  'Madagascar': '马达加斯加',
  'Malawi': '马拉维',
  'Malaysia': '马来西亚',
  'Maldives': '马尔代夫',
  'Mali': '马里',
  'Malta': '马耳他',
  'Martinique': '马提尼克',
  'Mauritania': '毛里塔尼亚',
  'Mauritius': '毛里求斯',
  'Mexico': '墨西哥',
  'Micronesia': '密克罗尼西亚联邦',
  'Moldova': '摩尔多瓦',
  'Monaco': '摩纳哥',
  'Mongolia': '蒙古',
  'Montenegro': '黑山',
  'Montserrat': '蒙特塞拉特',
  'Morocco': '摩洛哥',
  'Mozambique': '莫桑比克',
  'Myanmar': '缅甸',
  'Namibia': '纳米比亚',
  'Nepal': '尼泊尔',
  'Netherlands': '荷兰',
  'New Caledonia': '新喀里多尼亚',
  'New Zealand': '新西兰',
  'Nicaragua': '尼加拉瓜',
  'Niger': '尼日尔',
  'Nigeria': '尼日利亚',
  'Niue': '',
  'N. Mariana Is.': '北马里亚纳群岛',
  'Norway': '挪威',
  'Oman': '阿曼',
  'Palau': '帕劳',
  'Palestine': '巴勒斯坦',
  'Pakistan': '巴基斯坦',
  'Panama': '巴拿马',
  'Papua New Guinea': '巴布亚新几内亚',
  'Paraguay': '巴拉圭',
  'Peru': '秘鲁',
  'Philippines': '菲律宾',
  'Poland': '波兰',
  'Portugal': '葡萄牙',
  'Puerto Rico': '波多黎各',
  'Qatar': '卡塔尔',
  'Serbia': '塞尔维亚',
  'Congo': '刚果（布）',
  'Reunion': '留尼旺',
  'Romania': '罗马尼亚',
  'Russia': '俄罗斯',
  'Rwanda': '卢旺达',
  'San Marino': '圣马力诺',
  'São Tomé and Principe': '圣多美和普林西比',
  'Saint Helena': '圣赫勒拿、阿森松和特里斯坦-达库尼亚',
  'Saudi Arabia': '沙特阿拉伯',
  'Senegal': '塞内加尔',
  'Seychelles': '塞舌尔',
  'S. Geo. and S. Sandw. Is.': '南乔治亚和南桑威奇群岛',
  'Siachen Glacier': '锡亚琴冰川',
  'Sierra Leone': '塞拉利昂',
  'Singapore': '新加坡',
  'Slovakia': '斯洛伐克',
  'Slovenia': '斯洛文尼亚',
  'Solomon Is.': '所罗门群岛',
  'Somalia': '索马里',
  'Somaliland': '索马里兰',
  'South Africa': '南非',
  'S. Sudan': '南苏丹',
  'Spain': '西班牙',
  'Sri Lanka': '斯里兰卡',
  'St. Christopher-Nevis': '圣其茨和尼维斯',
  'Saint Lucia': '圣卢西亚',
  'St. Pierre and Miquelon': '圣皮埃尔和密克隆',
  'St. Vin. and Gren.': '圣文森特和格林纳丁斯',
  'Sudan': '苏丹',
  'Suriname': '苏里南',
  'Svalbard': '斯瓦尔巴和扬马延',
  'Swaziland': '斯威士兰',
  'Sweden': '瑞典',
  'Switzerland': '瑞士',
  'Syria': '叙利亚',
  'Taiwan': '台湾',
  'Tajikistan': '塔吉克斯坦',
  'Tanzania': '坦桑尼亚',
  'Thailand': '泰国',
  'Timor-Leste': '东帝汶',
  'Togo': '多哥',
  'Tonga': '汤加',
  'Trinidad and Tobago': '特立尼达和多巴哥',
  'Tunisia': '突尼斯',
  'Turkey': '土耳其',
  'Turkmenistan': '土库曼斯坦',
  'Turks and Caicos Is.': '特克斯和凯科斯群岛',
  'Uganda': '乌干达',
  'Ukraine': '乌克兰',
  'United Arab Emirates': '阿联酋',
  'United Kingdom': '英国',
  'United States': '美国',
  'U.S. Virgin Is.': '美属维尔京群岛',
  'Uruguay': '乌拉圭',
  'Uzbekistan': '乌兹别克斯坦',
  'Vanuatu': '瓦努阿图',
  'Venezuela': '委内瑞拉',
  'Vietnam': '越南',
  'W. Sahara': '西撒哈拉',
  'Samoa': '萨摩亚',
  'Yemen': '也门',
  'Yugoslavia': '南斯拉夫',
  'Zambia': '赞比亚',
  'Zimbabwe': '津巴布韦'
};

// iso 3166-1 country code to the country name in echarts map
const isoCountryToEchartsName = {
  AF: '阿富汗',
  AL: '阿尔巴尼亚',
  DZ: '阿尔及利亚',
  AD: '安道尔',
  AO: '安圭拉',
  AG: '安提瓜和巴布达',
  AR: '阿根廷',
  AM: '亚美尼亚',
  AT: '奥地利',
  AZ: '阿塞拜疆',
  BS: '巴哈马',
  BH: '巴林',
  BD: '孟加拉国',
  BB: '巴巴多斯',
  BY: '白俄罗斯',
  BE: '比利时',
  BZ: '伯利兹',
  BJ: '贝宁',
  BT: '不丹',
  BO: '玻利维亚',
  BA: '波斯尼亚和黑塞哥维那',
  BW: '博茨瓦纳',
  BR: '巴西',
  BN: '文莱',
  BG: '保加利亚',
  BF: '布基纳法索',
  MM: '缅甸',
  BI: '布隆迪',
  CV: '佛得角',
  KH: '柬埔寨',
  CM: '喀麦隆',
  CF: '中非共和国',
  TD: '乍得',
  CL: '智利',
  CO: '哥伦比亚',
  CG: '刚果（布）',
  CD: '刚果（金）',
  KM: '科摩罗',
  CR: '哥斯达黎加',
  CI: '科特迪瓦',
  HR: '克罗地亚',
  CU: '古巴',
  CY: '塞浦路斯',
  CZ: '捷克共和国',
  DK: '丹麦',
  DJ: '吉布提',
  DM: '多米尼加',
  DO: '多明尼加共和国',
  EC: '厄瓜多尔',
  EG: '埃及',
  SV: '萨尔瓦多',
  GQ: '赤道几内亚',
  ER: '厄立特里亚',
  EE: '爱沙尼亚',
  SZ: '斯威士兰',
  ET: '埃塞俄比亚',
  FJ: '斐济',
  FI: '芬兰',
  FR: '法国',
  GA: '加蓬',
  GM: '冈比亚',
  GE: '格鲁吉亚',
  DE: '德国',
  GH: '加纳',
  GR: '希腊',
  GD: '格林那达',
  GL: '格陵兰',
  GT: '危地马拉',
  GN: '几内亚',
  GW: '几内亚比绍',
  GY: '圭亚那',
  HT: '海地',
  VA: undefined,
  HN: '洪都拉斯',
  HU: '匈牙利',
  IS: '冰岛',
  IN: '印度',
  ID: '印度尼西亚',
  IR: '伊朗',
  IQ: '伊拉克',
  IE: '爱尔兰',
  IL: '以色列',
  IT: '意大利',
  JM: '牙买加',
  JP: '日本',
  JO: '约旦',
  KZ: '哈萨克斯坦',
  KE: '肯尼亚',
  KR: '韩国',
  XK: '科索沃',
  KW: '科威特',
  KG: '吉尔吉斯斯坦',
  LA: '老挝',
  LV: '拉脱维亚',
  LB: '黎巴嫩',
  LS: '莱索托',
  LR: '利比里亚',
  LY: '利比亚',
  LI: '列支敦士登',
  LT: '立陶宛',
  LU: '卢森堡',
  MG: '马达加斯加',
  MW: '马拉维',
  MY: '马来西亚',
  MV: '马尔代夫',
  ML: '马里',
  MT: '马耳他',
  MH: undefined,
  MR: '毛里塔尼亚',
  MU: '毛里求斯',
  MX: '墨西哥',
  FM: '密克罗尼西亚联邦',
  MD: '摩尔多瓦',
  MC: '摩纳哥',
  MN: '蒙古',
  ME: '黑山',
  MA: '摩洛哥',
  MZ: '莫桑比克',
  NA: '纳米比亚',
  NP: '尼泊尔',
  NL: '荷兰',
  NZ: '新西兰',
  NI: '尼加拉瓜',
  NE: '尼日尔',
  NG: '尼日利亚',
  MK: '马其顿',
  NO: '挪威',
  OM: '阿曼',
  PK: '巴基斯坦',
  PW: '帕劳',
  PA: '巴拿马',
  PG: '巴布亚新几内亚',
  PY: '巴拉圭',
  PE: '秘鲁',
  PH: '菲律宾',
  PL: '波兰',
  PT: '葡萄牙',
  QA: '卡塔尔',
  RO: '罗马尼亚',
  RU: '俄罗斯',
  RW: '卢旺达',
  KN: '圣其茨和尼维斯',
  LC: '圣卢西亚',
  VC: '圣文森特和格林纳丁斯',
  WS: '萨摩亚',
  SM: '圣马力诺',
  ST: '圣多美和普林西比',
  SA: '沙特阿拉伯',
  SN: '塞内加尔',
  RS: '塞尔维亚',
  SC: '塞舌尔',
  SL: '塞拉利昂',
  SG: '新加坡',
  SK: '斯洛伐克',
  SI: '斯洛文尼亚',
  SB: '所罗门群岛',
  SO: '索马里',
  ZA: '南非',
  SS: '南苏丹',
  ES: '西班牙',
  LK: '斯里兰卡',
  SD: '苏丹',
  SR: '苏里南',
  SE: '瑞典',
  CH: '瑞士',
  SY: '叙利亚',
  TW: '台湾',
  TJ: '塔吉克斯坦',
  TZ: '坦桑尼亚',
  TH: '泰国',
  TL: '东帝汶',
  TG: '多哥',
  TT: '特立尼达和多巴哥',
  TN: '突尼斯',
  TR: '土耳其',
  UG: '乌干达',
  UA: '乌克兰',
  AE: '阿联酋',
  GB: '英国',
  UY: '乌拉圭',
  UZ: '乌兹别克斯坦',
  VU: '瓦努阿图',
  VE: '委内瑞拉',
  VN: '越南',
  PS: '巴勒斯坦',
  EH: '西撒哈拉',
  YE: '也门',
  ZM: '赞比亚',
  ZW: '津巴布韦',
  AU: '澳大利亚',
  CA: '加拿大',
  CN: '中国',
  US: '美国'
};

// iso 3166-2 province code to the country name in echarts map
const isoProvinceToEchartsName = {
  'CN-AH': '安徽',
  'CN-BJ': '北京',
  'CN-CQ': '重庆',
  'CN-FJ': '福建',
  'CN-GD': '广东',
  'CN-GS': '甘肃',
  'CN-GX': '广西',
  'CN-GZ': '贵州',
  'CN-HA': '河南',
  'CN-HB': '湖北',
  'CN-HE': '河北',
  'CN-HI': '海南',
  'CN-HK': '香港',
  'CN-HL': '黑龙江',
  'CN-HN': '湖南',
  'CN-JL': '吉林',
  'CN-JS': '江苏',
  'CN-JX': '江西',
  'CN-LN': '辽宁',
  'CN-MO': '澳门',
  'CN-NM': '内蒙古',
  'CN-NX': '宁夏',
  'CN-QH': '青海',
  'CN-SC': '四川',
  'CN-SD': '山东',
  'CN-SH': '上海',
  'CN-SN': '陕西',
  'CN-SX': '山西',
  'CN-TJ': '天津',
  'CN-TW': '台湾',
  'CN-XJ': '新疆',
  'CN-XZ': '西藏',
  'CN-YN': '云南',
  'CN-ZJ': '浙江'
};

/*
const provinceFileNameMap = {
  '上海': 'Shanghai',
  '云南': 'Yunnan',
  '内蒙古': 'Neimenggu',
  '北京': 'Beijing',
  '台湾': 'Taiwan',
  '吉林': 'Jilin',
  '四川': 'Sichuan',
  '天津': 'Tianjin',
  '宁夏': 'Ningxia',
  '安徽': 'Anhui',
  '山东': 'Shandong',
  '山西': 'Shanxi',
  '广东': 'Guangdong',
  '广西': 'Guangxi',
  '新疆': 'Xinjiang',
  '江苏': 'Jiangsu',
  '江西': 'Jiangxi',
  '河北': 'Hebei',
  '河南': 'Henan',
  '浙江': 'Zhejiang',
  '海南': 'Hainan',
  '湖北': 'Hubei',
  '湖南': 'Hunan',
  '澳门': 'Macau',
  '甘肃': 'Gansu',
  '福建': 'Fujian',
  '西藏': 'Xicang',
  '贵州': 'Guizhou',
  '辽宁': 'Liaoning',
  '重庆': 'Chongqing',
  '陕西': 'Shaanxi',
  '青海': 'Qinghai',
  '香港': 'Hong Kong',
  '黑龙江': 'Heilongjiang',
  'world': 'World'
};
*/

export {
  nameMap,
  // provinceFileNameMap,
  isoCountryToEchartsName,
  isoProvinceToEchartsName
};
