/*  Simplied and enhanced version of fetch API  */
const serverURL = 'https://lab.isaaclin.cn/nCoV/api';
const RETRY_TIMES = 3;
let retryCount = 0;

function fetchJSON(api, init) {
  // If no response in 5 seconds, abort the request
  const controller = new AbortController();
  const signal = controller.signal;
  const id = setTimeout(() => controller.abort(), 6000);

  // Add timestamp to avoid cache result
  const requestURL = serverURL + api;

  const requestBody = JSON.stringify({
    ...init,
  });

  // return a promise generated by a 'post' fetch
  return fetch(requestURL, {
    method: 'post',
    headers: {'Content-Type': 'application/json;charset=utf-8'},
    body: requestBody,
    signal
  })
    .then((body) => {
      // cancel the abortion timer when response arrived
      clearTimeout(id);
      if (body.ok) {
        return body.json();
      } else {
        throw new Error('Request failed: ' +
          body.status + ' ' + body.statusText);
      }
    })
    // retry while request failed
    .catch((err) => {
      if (err.message.includes('404')) {
        alert('该资源不存在');
        return Promise.reject(err);
      } else if (retryCount > RETRY_TIMES) {
        retryCount = 0;
        console.log('请求超时，请重试。');
        console.log(err);
        if (err.name === 'AbortError') {
          alert('服务器长时间无响应，请检查您的网络');
          return Promise.reject(new Error('Request timeout'));
        }
      } else {
        // remind the user if retry for twice or more
        if (err.name === 'AbortError' && retryCount > 1) {
          alert('网络似乎有点慢，正在重试……');
        }
        retryCount++;
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve(fetchJSON(api, init));
          }, 500 * retryCount);
        });
      }
    });
}

export default fetchJSON;
